name: Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  typing:
    runs-on: "ubuntu-latest"

    name: Type checking
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: "3.10"

      - run: |
          pip install hatch
          hatch run checks:typing

  linting:
    runs-on: "ubuntu-latest"

    name: Linting
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: "3.10"

      - run: |
          pip install hatch
          hatch run checks:linting

  formatting:
    runs-on: "ubuntu-latest"

    name: Formatting
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: "3.10"

      - run: |
          pip install hatch
          hatch run checks:formatting
