name: Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  typing:
    runs-on: "ubuntu-latest"

    name: Type checking
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.10"

      - run: |
          pip install hatch
          hatch run checks:typing

  linting:
    runs-on: "ubuntu-latest"

    name: Linting
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.10"

      - run: |
          pip install hatch
          hatch run checks:linting

  formatting:
    runs-on: "ubuntu-latest"

    name: Formatting
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.10"

      - run: |
          pip install hatch
          hatch run checks:formatting
