name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install project
        run: pip install .
      - name: Run command
        run: |
          pip3 install riot
          riot -v run -s black -- --check .
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install project
        run: pip install .
      - name: Run command
        run: |
          pip3 install riot
          riot -v run -s mypy
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install project
        run: pip install .
      - name: Run command
        run: |
          pip3 install riot
          riot -v run -s flake8
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10", pypy-3.7]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Python 3 (for riot)
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install project
        run: |
          pip install setuptools
          pip install .
      - name: Run tests
        run: |
          python3.9 -m pip install riot
          riot -v run --python=${{ matrix.python-version }} test
