name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Check formatting
        run: |
          python -m pip install .[test]
          riot -v run -s black -- --check .
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install project
        run: pip install .
      - name: Run command
        run: |
          python -m pip install .[test]
          riot -v run -s mypy
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Run command
        run: |
          python -m pip install .[test]
          riot -v run -s flake8
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          docker run \
            --rm \
            -v $PWD:/work/envier \
            -w /work/envier \
            ghcr.io/datadog/envier/test:3f7d59e9cdb7b31259a3b1202b89fd0df3c2a3bc \
            bash -c "pip install .[test] && riot -v run smoke-test && riot -v run tests"
