name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    name: Test with Python ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          pip install hatch
          hatch run tests.py${{ matrix.python-version }}:tests
